apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"kboom","namespace":"kboom"},"spec":{"template":{"spec":{"containers":[{"command":["/kboom","--namespace=kboom","--mode=scale:14","--load=pods:10","--image=busybox"],"image":"quay.io/mhausenblas/kboom:2","name":"kboom"}],"restartPolicy":"Never","serviceAccountName":"kboom-sa"}}}}
    creationTimestamp: "2020-04-29T10:18:27Z"
    labels:
      controller-uid: 138b073d-1ddb-47c3-99af-5105d20f918e
      job-name: kboom
    name: kboom
    namespace: kboom
    resourceVersion: "1135643"
    selfLink: /apis/batch/v1/namespaces/kboom/jobs/kboom
    uid: 138b073d-1ddb-47c3-99af-5105d20f918e
  spec:
    backoffLimit: 6
    completions: 1
    parallelism: 1
    selector:
      matchLabels:
        controller-uid: 138b073d-1ddb-47c3-99af-5105d20f918e
    template:
      metadata:
        creationTimestamp: null
        labels:
          controller-uid: 138b073d-1ddb-47c3-99af-5105d20f918e
          job-name: kboom
      spec:
        containers:
        - command:
          - /kboom
          - --namespace=kboom
          - --mode=scale:14
          - --load=pods:10
          - --image=busybox
          image: quay.io/mhausenblas/kboom:2
          imagePullPolicy: IfNotPresent
          name: kboom
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: kboom-sa
        serviceAccountName: kboom-sa
        terminationGracePeriodSeconds: 30
  status:
    completionTime: "2020-04-29T10:22:13Z"
    conditions:
    - lastProbeTime: "2020-04-29T10:22:13Z"
      lastTransitionTime: "2020-04-29T10:22:13Z"
      status: "True"
      type: Complete
    startTime: "2020-04-29T10:18:27Z"
    succeeded: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
