apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: app
  replicas: 2
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
           - name: certs
             valueFrom:
               configMapRef: 
                 name: certs
                 key: certificate.crt
           - name: key
             valueFrom:
               configMapRef:
                 name: key
                 key: privateKey.key
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30004
  selector:
    run: app
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-labs
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: {{sriram}}
    password: {{admin123}}
    
    
---
apiVersion: v1
data:
  privatekey.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
QVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3ZSMGpEK2FWN3pRWCsKbk95OW81RnNaVHpBSENCRDFYWHpF
aEgvYUJINnY3cUpjTGZLSzZHUTRCZWxPa3J0ZlNvQVp5RHlBNVhnUHBWSApmM0RtMUhpKy9NZGQz
d0RGamRMcmxmOHZDTDlVdEtGaEttR04vWTVOYnJLZ3d6VXM0clk3c1ZzZjA1SnlYTUdZClcyZWtP
aTFJcDZkc1Q4MkpCZjgyUmh3SGpTWmtHTVhVVFpxa3U4VzJCcFpwVFBBeE9PL3FDMkhtWWJaMjhD
T1cKdi9IWlNPKzFkWS9NZGNQSEJhVkZ1QlpaczRock1hL2xrblhLRk5zaHZ6bjFvZytFWUY3eVc5
dFNXSE5RRlNxWgpDMG5FVThzdTB2WVgxNmsyaW9LL2tHTkV5WGJBVXpFMGdaaUdkWUIvcktCLzgx
di9tS2xZb3p5YUFSU3IvNGhiCi9VaVdqRVBiQWdNQkFBRUNnZ0VBZlNrNzdxVS80KzE5VUZraVBE
Q20wVzVoT1JWY2ZOUGF5OTJsZUdvS0hMSDQKTTlpSGhSZ3U0Tk1FVDNvV3N3dGppTElidG5XVStu
SDJDdjRYMHR6NTgvZHhMYmptUml1RjU3Qk9ibm1pbG92OQppUExJZ3FvQ2lZeDRoWStmVXhQNDZS
czJaTDJobjRSWXdjRFRlMVFIcmcvNTM4QUVsc252ZWdRS1UrSVkvZlA3CnYrZk9FbzJGV0s2Z0s5
V0RuUURnZ1RoNy96ME5OWjR6UUpBbzBHcHhKMnVTN2R1b2JiTXJhZ0dCOTRGZXJ1V1AKLytGbHoy
SXBzR1B5Uzhpa0ViZkRYeDRZY0VqVHlxK1JmS0hMQVdhR1RIVi9kcExad0w5WHU4Y2pNSmtNWDhs
YwpzMVhneHlHbWdWaWQ4bkUxcUpuYjB4Q09aYzk0M2NGRC8vYWJTenhWUVFLQmdRRGVSc09OU1Rm
NStYUmZsQ0ZJClg1amV2SkhBSGh2VmRjdU94bXJWYko1cE0zVGMrbjlacUhhNTlUZnUwV2FtM3RI
MHRMa0g2eDlUZHo3aUV4UE8KU3NlNStiQ3NZN1pwUmgrZkxaa0hhY0xMRnhldmN6R2N6bklzQm9q
cmFlS0tVdm9SQStJaFR3UzhjMWJMR3lBRwpkSHB6K052VEx0T0xIYnNTYXBMZlM2ZEVjUUtCZ1FE
SjN4MTNhZ0NoQzQxQTM2b1JFMjQybXVNVkJZWWI1TzRpCnpCYzVKc1U3M3gxUk81ZFppWENIN0Zz
Y0ROYStOV2ZNN2J0WUdFUXRJK0QzbnFuMUVMTjUwUkVGYnFkRXQxbVMKN0lSWWx1Mnc2NzJIdDdv
MTFILzNRbk1rQWVwQlQ1enBTVGJjazNpR1U1dC9HV2ZHdEJma3R2WjdPbDlWM1kyeQozVjU5ZFA4
REN3S0JnQWV2ZHE5NTZwK1FDb0FMaFNNVmV4bW9kM21uRU50T21WMDBheGs2Q2pnaytWTnlyZGlS
CnhKa2xhMnVzZmRvak5pczUzSFB6b3orbGpkMFBQODRRTTl1d1VIV0ZkUmNxdjRrbmNIVWJLUXNR
bjFjSHFwMTcKWGVNN3pwd2xLeG9SU0dneU5DMW1xQWxFQzZvMkkrTlZQNjZtMmlMeEtZdFQyZFlI
TFZEZk1zZGhBb0dCQUsvNAovMjIrQ01oYUVvc1ByZWR1d2E5MSt5ZXpCZ0hBNFZtU0FWaC9sSVVw
YkJ3SXoxbHN0cHkyQzRIN0t5THAyUTlKCjJQcmxSR0Q1R3IyZ0lOV1E5bkxsTFdwSDJDWE5rcGJC
K0dobFFOUHQyK3kzMnVuYjBLVVExdC8zajJYWmFaWHUKalpWZ05Ec2NITHVCd1BYMHZiTlJUckdD
NCtJczNMMmp2Uit0NGpLYkFvR0JBTE45QjdHVmwxRmw0VEV4VHJxTQpIMTh1ajVMd1NkeFJIVTU4
M2ovTzdtVUFDR2dxVGVaOTQwOVMrYW1ZbmtzUnhIbUlXbkhJWm1Nd29oS1JabXhpCms1a1VCYS9x
aCtYQXZrbG9zS0ZWM1BaUWY5QUlmc0h1NlA2UlY1WElIaWlWNXlvNFErbzEyZFpINmY1NDZDcEwK
NEwrZ0VFaEhzSlVnSFlmWlpmdnJPVUpuCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-29T11:12:21Z"
  name: certs
  namespace: labs
  resourceVersion: "1140954"
  selfLink: /api/v1/namespaces/labs/configmaps/certs
  uid: 4f528f4d-99c8-40c7-b812-9166e29292f7
---
apiVersion: v1
data:
 certificate.crt : |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtekNDQW9PZ0F3SUJBZ0lKQU9jSUlwTEcz
Y1M0TUEwR0NTcUdTSWIzRFFFQkN3VUFNR1F4Q3pBSkJnTlYKQkFZVEFuaDRNUXN3Q1FZRFZRUUlE
QUo0ZURFTU1Bb0dBMVVFQnd3RGVIaDRNUXd3Q2dZRFZRUUtEQU40ZUhneApEREFLQmdOVkJBc01B
M2g0ZURFTE1Ba0dBMVVFQXd3Q2VIZ3hFVEFQQmdrcWhraUc5dzBCQ1FFV0FuaDRNQjRYCkRUSXdN
RFF5T1RFeE1EZzBNRm9YRFRJeE1EUXlPVEV4TURnME1Gb3daREVMTUFrR0ExVUVCaE1DZUhneEN6
QUoKQmdOVkJBZ01Bbmg0TVF3d0NnWURWUVFIREFONGVIZ3hEREFLQmdOVkJBb01BM2g0ZURFTU1B
b0dBMVVFQ3d3RAplSGg0TVFzd0NRWURWUVFEREFKNGVERVJNQThHQ1NxR1NJYjNEUUVKQVJZQ2VI
Z3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZSMGpEK2FWN3pR
WCtuT3k5bzVGc1pUekFIQ0JEMVhYekVoSC8KYUJINnY3cUpjTGZLSzZHUTRCZWxPa3J0ZlNvQVp5
RHlBNVhnUHBWSGYzRG0xSGkrL01kZDN3REZqZExybGY4dgpDTDlVdEtGaEttR04vWTVOYnJLZ3d6
VXM0clk3c1ZzZjA1SnlYTUdZVzJla09pMUlwNmRzVDgySkJmODJSaHdICmpTWmtHTVhVVFpxa3U4
VzJCcFpwVFBBeE9PL3FDMkhtWWJaMjhDT1d2L0haU08rMWRZL01kY1BIQmFWRnVCWloKczRock1h
L2xrblhLRk5zaHZ6bjFvZytFWUY3eVc5dFNXSE5RRlNxWkMwbkVVOHN1MHZZWDE2azJpb0sva0dO
RQp5WGJBVXpFMGdaaUdkWUIvcktCLzgxdi9tS2xZb3p5YUFSU3IvNGhiL1VpV2pFUGJBZ01CQUFH
alVEQk9NQjBHCkExVWREZ1FXQkJRVHE4dm9JUzVWVUd1VmVSMnlucTdkVHpESnpUQWZCZ05WSFNN
RUdEQVdnQlFUcTh2b0lTNVYKVUd1VmVSMnlucTdkVHpESnpUQU1CZ05WSFJNRUJUQURBUUgvTUEw
R0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBQwpyTEIrRFZWYUQ2RHIwc254VDFCRloxb21UeTlQMzVE
OTUrTEtjWHpvMnd4ekFRNTgzaXRrOWNFL1NNcUJtaGZMCldTcFgyU3hiK3YvMXBvamlJSmpRYlEx
QkhBQTgrM0R0QVRUN2c3UnNYZEU4MkJSVFgzMUw1d0VXdmpyR2pMemQKRGlIOFBjOVJzemVhQ1R1
bVNCODdUeHc2dmpNQ1JqcnFrT2lLbzBXaGU2NGdXYjR4R2h4NytmV1I3LzIyUGgwTQp5bXExZDE5
RWRjd1BVazNPTC9pT3VRWXVUWGpoblVxdUR1YjlhTU9OQWtKUUhIVGV5M0FtVUdsZWJzakk3c0Nz
CjAzWE85aWhvRUlmdUlDZ25PeWY4Zy83Ny9XYWhrMU1jZ3IyRmJub0ZkNlJGYitndURlVDVobEpL
ejkzNDlUNVMKYm9YbjVJdEZDVmFQcUxtSGlNVlgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-29T11:13:18Z"
  name: key
  namespace: labs
  resourceVersion: "1141058"
  selfLink: /api/v1/namespaces/labs/configmaps/key
  uid: 4099a72e-d3f1-4e7c-a53d-1fdfb0ee077b

