apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: app
  replicas: 2
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
              resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
          
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30004
  selector:
    run: app
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-labs
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: {{sriram}}
    password: {{admin123}}
    
    

